# Example api requests

## User authentication

### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "newuser6",
  "password": "newpwexample",
  "email": "newuser6@example.com"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "newuser6",
  "password": "newpwexample"
}

### Get my user info
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3MzE5MjA1MDYsImV4cCI6MTczMjAwNjkwNn0.lsH2IFBtX7K83PGTaUfor3LWOgaGPPRflTA5kbCvVeA

## Media resource

### Get all media
GET http://localhost:3000/api/media

### Get a media item based on id
GET http://localhost:3000/api/media/4
### Get media item FAIL (id not found)
GET http://localhost:3000/api/media/96399

### Create an item
POST http://localhost:3000/api/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJpYXQiOjE3MzI1MjQ4ODksImV4cCI6MTczMjYxMTI4OX0.AxOzq2Jrjn-pgnYtECZ0TNjHxG57k8QSvyrtcADtu4Q
Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="title"

New cat image
------Boundary
Content-Disposition: form-data; name="description"

Kiva kuva kissasta.
------Boundary
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

< ./cat2.png
------Boundary--

### Create an item FAIL (title missing)
POST http://localhost:3000/api/media
Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="description"

Kiva kuva kissasta.
------Boundary
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

< ./cat2.png
------Boundary--

### Update an item
PUT http://localhost:3000/api/media/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3MzE5MjA1MDYsImV4cCI6MTczMjAwNjkwNn0.lsH2IFBtX7K83PGTaUfor3LWOgaGPPRflTA5kbCvVeA

{
  "title": "Muokattu kuva",
  "description": "Tosi kiva."
}
